### ISSUE TITLE
Scoring Strategy

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/QA-Tool#23]
How will we represent the scoring of the topic services at location? We will either be scoring these from 1 - 3 or 1 - 5. Is there a more descriptive calculation we could do to represent scores?

When comparing two alternative search implementation, we score them with 3 meaning a good result for a given query, 2 a not so good fit and 1 a poor fit. Compare two algorithms by counting how many 3 scores each get.

**Comment by ArtiBPG** [comment]
if you are making high, low, not relevant buttons, isnt it 1-3? https://github.com/pg-irc/QA-Tool/issues/18

**Comment by tomy-pg** [comment]
The scoring strategy has already been established. Services will be rated from a score of 1, 2 or 3, with 1 meaning not relevant, 2 being somewhat relevant and 3 being relevant. 

Once we have some services scored we can then just query the database for the services scored based on the algorithm URL, topic and location. This way, we will be able to see which algorithm achieved the greatest relevancy scores for each service list generated.
